language: node_js
node_js:
  - 4.2.1
install:
  - unzip node_modules.zip -d node_modules
  - npm install -g bower
  - npm install -g gulp
  - npm install -g gulp-jshint
  - npm install
  - bower install
before_script:
  - gulp build
script: gulp test